import Head from "next/head"
import { Oswald } from "@next/font/google"
import styles from "@/styles/Home.module.css"

const oswald = Oswald({ subsets: ["latin"] })

import { trpc } from "../utils/trpc"
import { signIn, signOut, useSession } from "next-auth/react"

export default function IndexPage() {
  const hello = trpc.hello.useQuery({ text: "client" })
  const { status, data } = useSession()

  console.log(status, data)

  return (
    <>
      <Head>
        <title>TRPC Test App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={oswald.className}>
          <h1>TRPC TEST APP</h1>
          {!data ? (
            <button onClick={() => signIn()}>Sign In</button>
          ) : (
            <button onClick={() => signOut()}>Sign Out</button>
          )}
          <div>
            {!hello.data ? <p>Loading...</p> : <p>{hello.data.greeting}</p>}
          </div>
        </div>
      </main>
    </>
  )
}
