import Head from "next/head"
import { Oswald } from "@next/font/google"
import styles from "@/styles/Home.module.css"

const oswald = Oswald({ subsets: ["latin"] })

import { trpc } from "../utils/trpc"

export default function IndexPage() {
  const hello = trpc.hello.useQuery({ text: "client" })

  return (
    <>
      <Head>
        <title>TRPC Test App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={oswald.className}>
          <h1>TRPC TEST APP</h1>
          <form className={styles.form}>
            <label htmlFor="email">Email</label>
            <input type="email" id="email" name="email" required />
            <label htmlFor="name">Name</label>
            <input type="text" id="name" name="name" />
          </form>
          <div>
            {!hello.data ? <p>Loading...</p> : <p>{hello.data.greeting}</p>}
          </div>
        </div>
      </main>
    </>
  )
}
