import Head from "next/head"
import styles from "@/styles/Home.module.css"

import { trpc } from "../utils/trpc"
import { signOut, useSession } from "next-auth/react"
import { useRouter } from "next/router"

export default function IndexPage() {
  const { status, data } = useSession()
  const router = useRouter()

  if (status !== "loading" && !data) router.push("/auth/signin")

  if (!data) return <div></div>

  const hello = trpc.hello.useQuery({ text: "client" })

  return (
    <>
      <Head>
        <title>TRPC Test App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1>TRPC TEST APP</h1>
        <button onClick={() => signOut()}>Sign Out</button>
        <div>
          {!hello.data ? <p>Loading...</p> : <p>{hello.data.greeting}</p>}
        </div>
      </div>
    </>
  )
}
