import Head from "next/head"
import Script from "next/script"

export type BaseLayoutPropsType = {
  title?: string
  description?: string
  children: React.ReactNode
}

export default function BaseLayout({
  title,
  description,
  children,
}: BaseLayoutPropsType) {
  return (
    <>
      <Head>
        <title>{title ? title : "TRPC Test App"}</title>
        <meta
          name="description"
          content={description ? description : "Generated by create next app"}
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script
        src="https://kit.fontawesome.com/c4aa491b21.js"
        crossOrigin="anonymous"
      ></Script>
      {children}
    </>
  )
}
